name: Simplified Webhook Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: This step will fail
        run: exit 1

      - name: Send Simple Webhook to Helios
        if: failure()
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.HELIOS_WEBHOOK_URL }}
          webhook_secret: "" # Not needed for this test
          data: '{ "repository": "test/simple-action", "commit_sha": "simple123", "logs": "This is a simplified test from a marketplace action." }'