name: Failing Workflow for Helios Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: This step is designed to fail
        run: |
          echo "This workflow will fail..."
          echo "The Helios CI GitHub App will automatically detect this failure."
          python -c "import non_existent_module"