- name: Report Failure to Helios CI
        if: failure()
        run: |
          # Get the job logs...
          JOB_ID=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs" | jq '.jobs[0].id')
          JOB_LOGS=$(curl --fail-with-body -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/jobs/$JOB_ID/logs")
          ESCAPED_LOGS=$(echo "$JOB_LOGS" | jq -Rsa .)

          # --- ADD THIS LINE TO DEBUG ---
          echo "Webhook URL being used: ${{ secrets.HELIOS_WEBHOOK_URL }}"

          # The original curl command
          curl --request POST \
          --url "${{ secrets.HELIOS_WEBHOOK_URL }}" \
          --header "Content-Type: application/json" \
          --data '{
            "repository": "${{ github.repository }}",
            "commit_sha": "${{ github.sha }}",
            "logs": '"$ESCAPED_LOGS"'
          }'